apiVersion: v1
kind: Deployment
metadata:
        labels:
                name: soldier
        name: testing-soldier
spec:
        replicas: 2
        template:
                metadata:
                        labels:
                                name: soldier
                spec:
                        containers:
                        - image: 9729232716/scale_registry:cicd_testimage
                          name: soldier
                          ports:
                          - name: soldier
                            containerPort: 8080

---
#Node Port service

apiVersion: v1
kind: Service
metadata:
        labels:
                name: soldier
        name: soldier
spec:
        type: NodePort
        ports:
                - port: 3000
                  targetPort: 8080
        selector:
                name: soldier

